site_name: Handbuch zur Erstellung einer digitalen Edition
site_dir: public
nav:
  - "Einleitung": "index.md"
  - "1. Planung":
      - "1_Planung/01_Projektziele_und_-ressourcen.md"
      - "1_Planung/02_Vorbildhafte_Editionen.md"
      - "1_Planung/03_Vernetzung.md"
  - "2. Editionsarbeit":
      - "2_Editionsarbeit/01_Einleitung_in_die_digitale_Editionsarbeit.md"
      - "2_Editionsarbeit/02_Textkonstitution.md"
      - "2_Editionsarbeit/03_Transkription.md"
      - "2_Editionsarbeit/04_converting.md"
      - "2_Editionsarbeit/05_semantic_annotation.md"
      - "2_Editionsarbeit/06_commenting.md"
  - "3. Präsentation":
      - "3_presentation/01_introduction_presentation.md"
      - "3_presentation/02_access.md"
      - "3_presentation/03_edition_views.md"
      - "3_presentation/04_timelines_maps.md"
      - "3_presentation/05_documentation.md"
  - "4. Langzeitsicherung":
      - "4_longterm_preservation/01_introduction_preservation.md"
      - "4_longterm_preservation/02_static_presentation.md"
      - "4_longterm_preservation/03_archiving_data.md"
  - "Themen":
      - "Themen/accessibility.md"
      - "Themen/authority.md"
      - "Themen/transkribus.md"
      - "Themen/tei.md"
      - "Themen/tei-publisher-annotations.md"

theme:
  language: de
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

  palette:
    primary: green
    accent: red

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - tags
  - glightbox
  - i18n:
      docs_structure: suffix
      languages:
        - locale: de
          default: true
          name: Deutsch
          build: true
        - locale: en
          name: English
          build: true
          site_name: "Manual for Creating a Digital Scholarly Edition"
          nav_translations:
            "Einleitung": Introduction
            "1. Planung": 1. Planning
            "2. Editionsarbeit": 2. Editorial work
            "3. Präsentation": 3. Presentation
            "4. Langzeitsicherung": 4. Long-term availability
            "Themen": Assorted topics
