site_name: Handbuch zur Erstellung einer digitalen Edition
site_dir: public
nav:
  - "Home": "index.md"
  - "Schritte":
      - "steps/atr.md"
      - "steps/critical_annotation.md"
      - "steps/converting.md"
      - "steps/commenting.md"
      - "steps/semantic_annotation.md"
  - "Publikationsplattform":
      - "publication/introduction.md"
  - "Langzeitarchivierung":
      - "preservation/introduction.md"
  - "Themen":
      - "topics/authority.md"

theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

  palette:
    primary: green
    accent: yellow

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
